// <auto-generated />
using ApiProduto.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProduto.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lshopping.ApiProduto.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            CategoriaNome = "Material Escolar"
                        },
                        new
                        {
                            CategoriaId = 2,
                            CategoriaNome = "Acessórios"
                        },
                        new
                        {
                            CategoriaId = 3,
                            CategoriaNome = "Eletrodomésticos"
                        },
                        new
                        {
                            CategoriaId = 4,
                            CategoriaNome = "Celulares"
                        },
                        new
                        {
                            CategoriaId = 5,
                            CategoriaNome = "Informática"
                        },
                        new
                        {
                            CategoriaId = 6,
                            CategoriaNome = "Eletrônicos"
                        },
                        new
                        {
                            CategoriaId = 7,
                            CategoriaNome = "Produtos do lar"
                        },
                        new
                        {
                            CategoriaId = 8,
                            CategoriaNome = "Vestuário"
                        },
                        new
                        {
                            CategoriaId = 9,
                            CategoriaNome = "Calçados"
                        },
                        new
                        {
                            CategoriaId = 10,
                            CategoriaNome = "Móveis"
                        });
                });

            modelBuilder.Entity("Lshopping.ApiProduto.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Lshopping.ApiProduto.Models.Produto", b =>
                {
                    b.HasOne("Lshopping.ApiProduto.Models.Categoria", "Categorias")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Lshopping.ApiProduto.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
